spring:
  profiles: local

  kafka:
    client-id: ${spring.application.name}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  cloud:
    bus:
      id: ${spring.application.name}-${random.uuid}
      enabled: true
      trace.enabled: true
      destination: config-server-bus.app
      abc: abc

management:
  endpoints.web.exposure.include: '*'
#  endpoint.health.probes.enabled: true
  health:
    probes.enabled: true
    binders.enabled: false

logging.level:
  org.springframework.cloud.config.server.encryption: error