name: Deploy to Heroku (spring-config-server-bus-simple)

on:
  push:
    branches:
      - main
    paths:
      - "spring-config-server-bus-simple/**"
      - ".github/workflows/config-server.yml"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-config-server https://heroku:${{secrets.HEROKU_API_TOKEN}}@git.heroku.com/${{secrets.HEROKU_CONFIG_SERVER_APP_NAME}}.git
      - name: Deploy backend to Heroku
        run: git push heroku-config-server `git subtree split --prefix spring-config-server-bus-simple main`:refs/heads/main --force